//
//  FBBundleInfo.h
//  EnvDetection
//
//  Created by 小七 on 2023/3/27.
//

#ifndef FBBundleInfo_h
#define FBBundleInfo_h

/* Generated by RuntimeBrowser
   Image: /System/Library/PrivateFrameworks/FrontBoard.framework/FrontBoard
 */

@interface FBBundleInfo : NSObject {
    NSString * _bundleIdentifier;
    NSString * _bundleType;
    NSURL * _bundleURL;
    NSString * _bundleVersion;
    NSUUID * _cacheGUID;
    NSString * _displayName;
    unsigned long long  _sequenceNumber;
}

@property (nonatomic, readonly, copy) NSString *bundleIdentifier;
@property (nonatomic, readonly, copy) NSString *bundleType;
@property (nonatomic, readonly) NSURL *bundleURL;
@property (nonatomic, readonly, copy) NSString *bundleVersion;
@property (nonatomic, readonly, copy) NSUUID *cacheGUID;
@property (readonly, copy) NSString *debugDescription;
@property (readonly, copy) NSString *description;
@property (nonatomic, readonly, copy) NSString *displayName;
@property (readonly) unsigned long long hash;
@property (nonatomic, readonly) unsigned long long sequenceNumber;
@property (readonly) Class superclass;

//- (void).cxx_destruct;
- (id)_initWithBundleIdentifier:(id)arg1 url:(id)arg2;
- (id)_initWithBundleProxy:(id)arg1 bundleIdentifier:(id)arg2 url:(id)arg3;
- (id)_initWithBundleProxy:(id)arg1 overrideURL:(id)arg2;
- (id)bundleIdentifier;
- (id)bundleType;
- (id)bundleURL;
- (id)bundleVersion;
- (id)cacheGUID;
- (id)debugDescription;
- (id)description;
- (id)descriptionBuilderWithMultilinePrefix:(id)arg1;
- (id)descriptionWithMultilinePrefix:(id)arg1;
- (id)displayName;
- (id)init;
- (unsigned long long)sequenceNumber;
- (id)succinctDescription;
- (id)succinctDescriptionBuilder;

@end

#endif /* FBBundleInfo_h */
